packages:
  - "apps/*"
  - "packages/*"
  - "packages/**/*"

catalog:
  typescript: 6.0.3
  react: 19.2.5
  react-dom: 19.2.5
  "@tanstack/react-router": 1.169.1
  "@tanstack/react-query": 5.100.8
  "@tanstack/react-start": 1.167.60
  tailwindcss: 4.2.4
  "@biomejs/biome": 2.4.14
