/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ConnectionRouteImport } from './routes/connection'
import { Route as BrowseRouteRouteImport } from './routes/browse/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as BrowseWingIndexRouteImport } from './routes/browse/$wing/index'
import { Route as BrowseWingRoomRouteImport } from './routes/browse/$wing/$room'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionRoute = ConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRouteRoute = BrowseRouteRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseRouteRoute,
} as any)
const BrowseWingIndexRoute = BrowseWingIndexRouteImport.update({
  id: '/$wing/',
  path: '/$wing/',
  getParentRoute: () => BrowseRouteRoute,
} as any)
const BrowseWingRoomRoute = BrowseWingRoomRouteImport.update({
  id: '/$wing/$room',
  path: '/$wing/$room',
  getParentRoute: () => BrowseRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteRouteWithChildren
  '/connection': typeof ConnectionRoute
  '/search': typeof SearchRoute
  '/browse/': typeof BrowseIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/browse/$wing/$room': typeof BrowseWingRoomRoute
  '/browse/$wing/': typeof BrowseWingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
  '/search': typeof SearchRoute
  '/browse': typeof BrowseIndexRoute
  '/graph': typeof GraphIndexRoute
  '/browse/$wing/$room': typeof BrowseWingRoomRoute
  '/browse/$wing': typeof BrowseWingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteRouteWithChildren
  '/connection': typeof ConnectionRoute
  '/search': typeof SearchRoute
  '/browse/': typeof BrowseIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/browse/$wing/$room': typeof BrowseWingRoomRoute
  '/browse/$wing/': typeof BrowseWingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/connection'
    | '/search'
    | '/browse/'
    | '/graph/'
    | '/browse/$wing/$room'
    | '/browse/$wing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connection'
    | '/search'
    | '/browse'
    | '/graph'
    | '/browse/$wing/$room'
    | '/browse/$wing'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/connection'
    | '/search'
    | '/browse/'
    | '/graph/'
    | '/browse/$wing/$room'
    | '/browse/$wing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRouteRoute: typeof BrowseRouteRouteWithChildren
  ConnectionRoute: typeof ConnectionRoute
  SearchRoute: typeof SearchRoute
  GraphIndexRoute: typeof GraphIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection': {
      id: '/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof ConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof BrowseRouteRoute
    }
    '/browse/$wing/': {
      id: '/browse/$wing/'
      path: '/$wing'
      fullPath: '/browse/$wing/'
      preLoaderRoute: typeof BrowseWingIndexRouteImport
      parentRoute: typeof BrowseRouteRoute
    }
    '/browse/$wing/$room': {
      id: '/browse/$wing/$room'
      path: '/$wing/$room'
      fullPath: '/browse/$wing/$room'
      preLoaderRoute: typeof BrowseWingRoomRouteImport
      parentRoute: typeof BrowseRouteRoute
    }
  }
}

interface BrowseRouteRouteChildren {
  BrowseIndexRoute: typeof BrowseIndexRoute
  BrowseWingRoomRoute: typeof BrowseWingRoomRoute
  BrowseWingIndexRoute: typeof BrowseWingIndexRoute
}

const BrowseRouteRouteChildren: BrowseRouteRouteChildren = {
  BrowseIndexRoute: BrowseIndexRoute,
  BrowseWingRoomRoute: BrowseWingRoomRoute,
  BrowseWingIndexRoute: BrowseWingIndexRoute,
}

const BrowseRouteRouteWithChildren = BrowseRouteRoute._addFileChildren(
  BrowseRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRouteRoute: BrowseRouteRouteWithChildren,
  ConnectionRoute: ConnectionRoute,
  SearchRoute: SearchRoute,
  GraphIndexRoute: GraphIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
